version: "3.9"

x-node-app: &node-app
  build: .
  networks:
    - harperdb-cluster

x-node-hdb: &node-hdb
  image: harperdb/harperdb
  environment:
    HDB_ADMIN_PASSWORD: "changeme"
    HDB_HTTP_PORT: "9925"
    HDB_ENABLE_AUTO_START: "true"
    CLUSTERING_ENABLED: "true"
    CLUSTERING_USER: "cluster_user"
    CLUSTERING_PASSWORD: "cluster_pass_123"
  networks:
    - harperdb-cluster

services:
  # Node 1
  node-1-app:
    <<: *node-app
    ports:
      - "3001:3000"
    environment:
      HARPERDB_URL: "http://node-1-hdb:9925"
      HARPERDB_USERNAME: "HDB_ADMIN"
      HARPERDB_PASSWORD: "changeme"
      HARPERDB_SCHEMA: "cheatercheck"
      HARPERDB_TABLE: "signals"
    depends_on:
      - node-1-hdb

  node-1-hdb:
    <<: *node-hdb
    ports:
      - "9925:9925"
      - "9926:9926"
      - "9932:9932"
    environment:
      HDB_ADMIN_PASSWORD: "changeme"
      HDB_HTTP_PORT: "9925"
      HDB_ENABLE_AUTO_START: "true"
      CLUSTERING_ENABLED: "true"
      CLUSTERING_USER: "cluster_user"
      CLUSTERING_PASSWORD: "cluster_pass_123"
      CLUSTERING_NODENAME: "Node1"
    volumes:
      - node-1-data:/opt/harperdb/hdb

  # Node 2
  node-2-app:
    <<: *node-app
    ports:
      - "3002:3000"
    environment:
      HARPERDB_URL: "http://node-2-hdb:9925"
      HARPERDB_USERNAME: "HDB_ADMIN"
      HARPERDB_PASSWORD: "changeme"
      HARPERDB_SCHEMA: "cheatercheck"
      HARPERDB_TABLE: "signals"
    depends_on:
      - node-2-hdb

  node-2-hdb:
    <<: *node-hdb
    ports:
      - "9927:9925"
      - "9928:9926"
      - "9933:9932"
    environment:
      HDB_ADMIN_PASSWORD: "changeme"
      HDB_HTTP_PORT: "9925"
      HDB_ENABLE_AUTO_START: "true"
      CLUSTERING_ENABLED: "true"
      CLUSTERING_USER: "cluster_user"
      CLUSTERING_PASSWORD: "cluster_pass_123"
      CLUSTERING_NODENAME: "Node2"
    volumes:
      - node-2-data:/opt/harperdb/hdb

  # Node 3
  node-3-app:
    <<: *node-app
    ports:
      - "3003:3000"
    environment:
      HARPERDB_URL: "http://node-3-hdb:9925"
      HARPERDB_USERNAME: "HDB_ADMIN"
      HARPERDB_PASSWORD: "changeme"
      HARPERDB_SCHEMA: "cheatercheck"
      HARPERDB_TABLE: "signals"
    depends_on:
      - node-3-hdb

  node-3-hdb:
    <<: *node-hdb
    ports:
      - "9929:9925"
      - "9930:9926"
      - "9934:9932"
    environment:
      HDB_ADMIN_PASSWORD: "changeme"
      HDB_HTTP_PORT: "9925"
      HDB_ENABLE_AUTO_START: "true"
      CLUSTERING_ENABLED: "true"
      CLUSTERING_USER: "cluster_user"
      CLUSTERING_PASSWORD: "cluster_pass_123"
      CLUSTERING_NODENAME: "Node3"
    volumes:
      - node-3-data:/opt/harperdb/hdb

networks:
  harperdb-cluster:
    driver: bridge

volumes:
  node-1-data:
  node-2-data:
  node-3-data:
